### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by devxpy** [GooeyAI/typescript-sdk#8]
- [ ] Auth keys via .env file + shell env vars + manually from code
- [ ] Default fields to Not Given and don't pass them to the server (eg openai SDK does this too)
- [ ] Typed request as kwargs & response objects -- only return the inner  (`.output` content by default)
- [ ] Simpler interface (eg `client.webSearchGpt3({ search_query: "..." })`) that calls the Async (v3) polling api (remove v2 support completely)
- [ ] Future compatible naming scheme that is based on URL, not the title of the endpoint (eg `webSearchGpt3` -> `googleGpt`)
- [ ] Retries
- [ ] support for our url structure - examples and runs
- — DEPLOY —
- [ ] ability to change the base URL (ie [api.gooey.ai](http://api.gooey.ai/) → [api.mysite.ai](http://api.mysite.ai/))
- [ ] docstrings for each field from openapi description
- [ ] Ability to obtain the outer response (run_id, web_url etc) if requested by the user
- [ ] Integrations Streaming api support as a generator protocol
- [ ] Support for an explicit Timeout
